FROM ghcr.io/metal-stack/rethinkdb-backup-tools-build:latest AS rethinkdb-backup-tools

FROM rethinkdb:2.4.4-bookworm-slim
COPY --from=rethinkdb-backup-tools /rethinkdb-dump /rethinkdb-restore /rethinkdb/
